'use client';

import { motion } from 'framer-motion';
import { Brain, Smartphone, DollarSign, Video } from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'Smart Itinerary Generator',
    description: 'AI-powered planning that creates personalized schedules based on your preferences, time, and budget.',
  },
  {
    icon: Smartphone,
    title: 'Local App Recommendations',
    description: 'Get curated lists of essential apps for transportation, dining, events, and local experiences.',
  },
  {
    icon: DollarSign,
    title: 'Budget Optimization',
    description: 'Intelligent cost analysis and suggestions to help you travel smarter and save money.',
  },
  {
    icon: Video,
    title: 'AI Travel Video',
    description: 'Immersive video previews generated by AI to help you visualize your trip before booking.',
  },
];

export default function FeaturesGrid() {
  return (
    <section id="features" className="py-24 px-6 max-w-7xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 50 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        viewport={{ once: true }}
        className="text-center mb-20"
      >
        <motion.div
          initial={{ scale: 0.8 }}
          whileInView={{ scale: 1 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
        >
          <h2 className="text-4xl md:text-5xl font-black text-white mb-6">
            Why Choose AI Travel Planning?
          </h2>
          <div className="w-24 h-1 bg-gradient-to-r from-purple-500 via-pink-500 to-blue-500 mx-auto mb-6 rounded-full"></div>
        </motion.div>
        <p className="text-gray-300 text-lg max-w-2xl mx-auto leading-relaxed">
          Experience the future of travel planning with cutting-edge AI technology that
          transforms how you discover and explore the world.
        </p>
      </motion.div>

      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
        {features.map((feature, index) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 50 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: index * 0.15 }}
            viewport={{ once: true }}
            whileHover={{ y: -15, boxShadow: '0 20px 50px rgba(168, 85, 247, 0.3)' }}
            className="group bg-white/10 backdrop-blur-lg rounded-2xl p-8 shadow-xl border border-white/20 hover:bg-white/15 transition-all duration-300 cursor-pointer overflow-hidden relative"
          >
            {/* Gradient Overlay */}
            <div className="absolute inset-0 bg-gradient-to-br from-purple-500/0 to-blue-500/0 group-hover:from-purple-500/10 group-hover:to-blue-500/10 transition-all duration-300"></div>
            
            <div className="relative z-10">
              <motion.div
                whileHover={{ scale: 1.2, rotate: 5 }}
                className="w-14 h-14 bg-gradient-to-br from-purple-500 to-blue-500 rounded-xl flex items-center justify-center mb-6 group-hover:shadow-2xl group-hover:shadow-purple-500/50 transition-all"
              >
                <feature.icon className="w-7 h-7 text-white" />
              </motion.div>
              <h3 className="text-xl font-bold text-white mb-3 group-hover:text-transparent group-hover:bg-gradient-to-r group-hover:from-purple-400 group-hover:to-blue-400 group-hover:bg-clip-text transition-all">
                {feature.title}
              </h3>
              <p className="text-gray-400 leading-relaxed group-hover:text-gray-300 transition-colors">
                {feature.description}
              </p>
            </div>

            {/* Bottom Border Accent */}
            <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-purple-500/0 via-pink-500 to-blue-500/0 group-hover:opacity-100 opacity-0 transition-opacity duration-300"></div>
          </motion.div>
        ))}
      </div>
    </section>
  );
}